### ISSUE TITLE
Circleci docker image needs to be rebuilt in pull requests

### ISSUE THREAD

**Issue by shoshber** [poldracklab/preprocessing-workflow#77] opened 2016-06-23 22:39 UTC
see https://github.com/poldracklab/preprocessing-workflow/pull/71

for when/why it isn't rebuilt

**Comment by oesteban** [comment] 2016-07-18 16:45
Since in #71 we've seen that this issue is not confirmed, the problem being for a different reason, I'll close this one.

**Closed by oesteban** 2016-07-18 16:45 UTC
